SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[W_SAP_SPP_BALANCE_F]
(
	PLANT_WID						INT 			NULL
	, DATE_WID						VARCHAR(8)		NULL
	, MATERIAL_WID					INT				NULL

	, [PERIOD] 						DATE 			NULL
	, [QUANTITY] 					DECIMAL(38, 20) NULL
	, [AMOUNT] 						DECIMAL(38, 20)	NULL
	

	, [PLANT] 						NVARCHAR(10) 	NULL
	, [MATERIAL_NUMBER] 			NVARCHAR(50) 	NULL
	, [TYPE] 						NVARCHAR(50) 	NULL
	

	, [PLANT_CODE] 					NVARCHAR(10) 	NULL

	, [STORAGE_LOCATION] 			NVARCHAR(50) 	NULL
	, [COMPANY_CODE] 				NVARCHAR(50) 	NULL
	, [VALUATION_AREA] 				NVARCHAR(50) 	NULL
	, [VALUATION_CLASS] 			NVARCHAR(50) 	NULL
	, [MATERIAL_TYPE] 				NVARCHAR(50) 	NULL
	, [MATERIAL_GROUP] 				NVARCHAR(50) 	NULL
	, [PURCHASING_GROUP] 			NVARCHAR(50) 	NULL
	, [BASE_UNIT_OF_MEASURE] 		NVARCHAR(50) 	NULL
	, [CURRENCY] 					NVARCHAR(50) 	NULL
	, [PRICE_CONTROL] 				NVARCHAR(50) 	NULL

	, [< 4 MONTHS]					DECIMAL(38, 20)	NULL
	, [4 - 12 MONTHS]				DECIMAL(38, 20)	NULL
	, [1 - 2 YEARS]					DECIMAL(38, 20)	NULL
	, [2 - 3 YEARS]					DECIMAL(38, 20)	NULL
	, [3 - 4 YEARS]					DECIMAL(38, 20)	NULL
	, [4 - 5 YEARS]					DECIMAL(38, 20)	NULL
	, [> 5 YEARS]					DECIMAL(38, 20)	NULL
	, [AGE_NULL]					DECIMAL(38, 20)	NULL

	, [MAX] 						DECIMAL(38, 20)	NULL
	, [MIN] 						DECIMAL(38, 20)	NULL
	, [OVER_MAX]					DECIMAL(38, 20)	NULL
	, [UNDER_MIN]					DECIMAL(38, 20)	NULL
	, [SLOW_MOVING]					DECIMAL(38, 20)	NULL


    , W_DELETE_FLG             		VARCHAR(1) 		NULL
	, W_DATASOURCE_NUM_ID       	INT 			NULL
	, W_INSERT_DT               	DATETIME2 		NULL
	, W_UPDATE_DT               	DATETIME2 		NULL
	, W_BATCH_ID                	NVARCHAR(50) 	NULL
	, W_INTEGRATION_ID          	NVARCHAR(200) 	NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO