SELECT TOP 100
    INVE.INVE_ID                AS INVE_WID
    , INVE.SITE_ID              AS [LOCATION]
    , INVE.ITEM_NUMBER          AS ITEM_CODE
    , ITEM.[DESCRIPTION]        AS ITEM_DESC
    , ITEM.SPVB_PRODUCTLINE     AS [LINE]
    , ITEM.SPVB_MACHINE         AS MACHINE
    , NULL                      AS [TYPE]
    , INVE.C
FROM STG.W_CMMS_INVE_FS INVE 
LEFT JOIN STG.W_CMMS_ITEM_DS ITEM ON 1=1
    AND ITEM.ITEM_NUM = INVE.ITEM_NUMBER
LEFT JOIN STG.W_CMMS_INVC_DS INVC ON 1=1
    AND INVC.ITEM_NUM = INVE.ITEM_NUM
    AND INVC.INVE_ID = INVE.INVE_ID
select top 10 * from STG.W_CMMS_ITEM_DS
select top 10 * from STG.W_CMMS_INVE_FS
