SELECT TOP 100
    ISNULL(PLANT.PLANT_WID, 0)                      AS PLANT_WID
    , ISNULL(WO_STA_APPRV.ASSET_WID, 0)             AS WO_STA_APPRV_WID
    , ISNULL(WO_STA_FINSH.ASSET_WID, 0)             AS WO_STA_FINSH_WID
    , ISNULL(WO_STA_COMPLT.ASSET_WID, 0)            AS WO_STA_COMPLT_WID
    , ISNULL(WO_STA_COMP.ASSET_WID, 0)              AS WO_STA_COMP_WID

    , CONVERT(NVARCHAR(30), WONUM)                  AS WORK_ORDERS
    , CONVERT(NVARCHAR(100), WO.[DESCRIPTION])      AS [DESCRIPTION]
    , CONVERT(nvarchar(5), WORKTYPE)                AS [TYPE]
    , CASE WHEN SPVB_OVERHAUL = 'False'
        THEN 'N' ELSE 'Y' END                       AS OVERHAUL
    , CONVERT(NVARCHAR(50), PMNUM)                  AS PM
    , CONVERT(NVARCHAR(50), JPNUM)                  AS JOB_PLAN
    , CONVERT(NVARCHAR( 5), SITEID)                 AS [SITE]
    , CONVERT(NVARCHAR(50), WO.[LOCATION])          AS [LOCATION]
    , CONVERT(NVARCHAR(30), ASSETNUM)               AS ASSET_NUM
    , CONVERT(NVARCHAR(10), WO.[STATUS])            AS [STATUS]
    , CONVERT(NVARCHAR(10), [SUPERVISOR])           AS [SUPERVISOR]
    , CONVERT(DATETIMEOFFSET, REPORTDATE)           AS DATE_CREATION
    , CONVERT(DATETIMEOFFSET, TARGSTARTDATE)        AS DATE_TARGET_START
    , CONVERT(DATETIMEOFFSET, SCHEDFINISH)          AS DATE_TARGET_FINISH
    , CONVERT(DATETIMEOFFSET, SCHEDSTART)           AS DATE_SCHEDULE_START
    , CONVERT(DATETIMEOFFSET, SCHEDFINISH)          AS DATE_SCHEDULE_FINISH    
    , CONVERT(DATETIMEOFFSET, WO_STA_APPRV.DATE)    AS DATE_APPROVED
    , CONVERT(DATETIMEOFFSET, WO_STA_FINSH.DATE)    AS DATE_FINISHED
    , CONVERT(DATETIMEOFFSET, WO_STA_COMPLT.DATE)   AS DATE_ACCEPTED
    , CONVERT(DATETIMEOFFSET, WO_STA_COMP.DATE)     AS DATE_COMPLETED
    , NULL AS JOB_DESCRIPTION   -- NOTE: cần join với table JOBPLAN nhưng không có
    , NULL AS SUPERVISOR_NAME -- NOTE: Cần join với table Person nhưng không có table


    , CONVERT(
        NVARCHAR(300), 
        CONCAT_WS('~', WONUM, ASSETNUM, TARGSTARTDATE, REPORTDATE)
	)                                               AS W_INTEGRATION_ID
    , 'N'                                           AS W_DELETE_FLG
    , 1                                             AS W_DATASOURCE_NUM_ID
    , GETDATE()                                     AS W_INSERT_DT
    , GETDATE()                                     AS W_UPDATE_DT
    , NULL                                          AS W_BATCH_ID
FROM [FND].[W_CMMS_WO_F] WO
    LEFT JOIN [dbo].[W_PLANT_SAP_D] PLANT ON 1=1
        AND PLANT.PLANT_NAME_2 = LEFT(WO.LOCATION, 3)
    LEFT JOIN [dbo].[W_CMMS_LOC_D] LOC ON 1=1
        AND LOC.LOCATION = WO.LOCATION
    LEFT JOIN [dbo].[W_CMMS_WO_STATUS_D] WO_STA_APPRV ON 1=1
        AND WO_STA_APPRV.WO_NUM = WO.WONUM
        AND WO_STA_APPRV.STATUS = 'APPR'
    LEFT JOIN [dbo].[W_CMMS_WO_STATUS_D] WO_STA_FINSH ON 1=1
        AND WO_STA_FINSH.WO_NUM = WO.WONUM
        AND WO_STA_FINSH.STATUS = 'FINISHED'
    LEFT JOIN [dbo].[W_CMMS_WO_STATUS_D] WO_STA_COMPLT ON 1=1
        AND WO_STA_COMPLT.WO_NUM = WO.WONUM
        AND WO_STA_COMPLT.STATUS = 'COMPLETED'
    LEFT JOIN [dbo].[W_CMMS_WO_STATUS_D] WO_STA_COMP ON 1=1
        AND WO_STA_COMP.WO_NUM = WO.WONUM
        AND WO_STA_COMP.STATUS = 'WO_STA_COMP'
WHERE 1=1
    AND wo.ISTASK = 'False'
    AND wo.WORKTYPE IN ('PM', 'CM')