SELECT TOP 100
    ISNULL(PLANT.PLANT_WID, 0)                          AS PLANT_WID
    , ISNULL(AST.LOCATION_WID, 0)                       AS LOC_WID
    , FORMAT(CONVERT(DATE, SCHEDSTART), 'yyyymmdd')     AS DATE_WID
    , ISNULL(AST.ASSET_WID, 0)                          AS ASSET_WID

    , CONVERT(NVARCHAR(30), WONUM)                      AS WORK_ORDERS
    , CONVERT(NVARCHAR(100), WO.[DESCRIPTION])          AS [DESCRIPTION]
    , CONVERT(nvarchar(5), WORKTYPE)                    AS [TYPE]
    , CASE WHEN SPVB_OVERHAUL = 'False'
        THEN 'N' ELSE 'Y' END                           AS OVERHAUL
    , CONVERT(NVARCHAR(50), PMNUM)                      AS PM
    , CONVERT(NVARCHAR(50), JPNUM)                      AS JOB_PLAN
    , CONVERT(NVARCHAR( 5), SITEID)                     AS [SITE]
    , CONVERT(NVARCHAR(50), WO.[LOCATION])              AS [LOCATION]
    , CONVERT(NVARCHAR(30), ASSETNUM)                   AS ASSET_NUM
    , CONVERT(NVARCHAR(10), WO.[STATUS])                AS [STATUS]
    , CONVERT(NVARCHAR(10), [SUPERVISOR])               AS [SUPERVISOR]
    , CONVERT(DATETIMEOFFSET, REPORTDATE)               AS DATE_CREATION
    , CONVERT(DATETIMEOFFSET, TARGSTARTDATE)            AS DATE_TARGET_START
    , CONVERT(DATETIMEOFFSET, SCHEDFINISH)              AS DATE_TARGET_FINISH
    , CONVERT(DATETIMEOFFSET, SCHEDSTART)               AS DATE_SCHEDULE_START
    , CONVERT(DATETIMEOFFSET, SCHEDFINISH)              AS DATE_SCHEDULE_FINISH
    , CONVERT(DATETIMEOFFSET, WO_STA_PLN.CHANGEDATE)    AS DATE_PLANNING
    , CONVERT(DATETIMEOFFSET, WO_STA_APPRV.CHANGEDATE)  AS DATE_APPROVED
    , CONVERT(DATETIMEOFFSET, WO_STA_FINSH.CHANGEDATE)  AS DATE_FINISHED
    , CONVERT(DATETIMEOFFSET, WO_STA_COMPLT.CHANGEDATE) AS DATE_ACCEPTED
    , CONVERT(DATETIMEOFFSET, WO_STA_COMP.CHANGEDATE)   AS DATE_COMPLETED
    , NULL AS JOB_DESCRIPTION   -- NOTE: cần join với table JOBPLAN nhưng không có
    , NULL AS SUPERVISOR_NAME   -- NOTE: Cần join với table Person nhưng không có table

    , CONVERT(
        NVARCHAR(300), 
        CONCAT_WS('~', WONUM, ASSETNUM, 
                PMNUM, SUPERVISOR, JPNUM)
    )                                               AS W_INTEGRATION_ID
    , 'N'                                           AS W_DELETE_FLG
    , 'N' 											AS W_UPDATE_FLG
    , 1                                             AS W_DATASOURCE_NUM_ID
    , GETDATE()                                     AS W_INSERT_DT
    , GETDATE()                                     AS W_UPDATE_DT
    , NULL                                          AS W_BATCH_ID
-- INTO #W_CMMS_WO_F_tmp
FROM [FND].[W_CMMS_WO_F] WO
    LEFT JOIN [dbo].[W_PLANT_SAP_D] PLANT ON 1=1
        AND PLANT.PLANT_NAME_2 = LEFT(WO.LOCATION, 3)
    LEFT JOIN [FND].[W_CMMS_WO_STATUS_D] WO_STA_PLN ON 1=1
        AND WO_STA_PLN.PARENT = WO.WONUM
        AND WO_STA_PLN.STATUS = 'PLANNING'
    LEFT JOIN [FND].[W_CMMS_WO_STATUS_D] WO_STA_APPRV ON 1=1
        AND WO_STA_APPRV.PARENT = WO.WONUM
        AND WO_STA_APPRV.STATUS = 'APPR'
    LEFT JOIN [FND].[W_CMMS_WO_STATUS_D] WO_STA_FINSH ON 1=1
        AND WO_STA_FINSH.PARENT = WO.WONUM
        AND WO_STA_FINSH.STATUS = 'FINISHED'
    LEFT JOIN [FND].[W_CMMS_WO_STATUS_D] WO_STA_COMPLT ON 1=1
        AND WO_STA_COMPLT.PARENT = WO.WONUM
        AND WO_STA_COMPLT.STATUS = 'COMPLETED'
    LEFT JOIN [FND].[W_CMMS_WO_STATUS_D] WO_STA_COMP ON 1=1
        AND WO_STA_COMP.PARENT = WO.WONUM
        AND WO_STA_COMP.STATUS = 'COMP'
    LEFT JOIN [dbo].[W_CMMS_LOC_D] LOC_X ON 1=1
        AND LOC_X.[LOCATION] = LEFT(WO.[LOCATION], 7)
    LEFT JOIN [dbo].[W_CMMS_ASSET_D] AST ON 1=1
        AND AST.[ASSET_NUM] = WO.[ASSETNUM]
WHERE 1=1
    AND wo.ISTASK = 'False'
    AND wo.WORKTYPE IN ('PM', 'CM') 