SELECT TOP 100
    BUDAT AS DATE_WID
    , ISNULL(PRODUCT.PRODUCT_WID, 0) AS PRODUCT_WID
    , ISNULL(PLANT.PLANT_WID, 0) AS PLANT_WID
    , 0 AS ASSET_WID
    , WERKS AS PLANT_CODE
    , BUKRS AS COMPANY_CODE
    , BSTAUS_SG AS STOCK_STATUS
    , WAERS AS CURRENCY_CODE
    , DMBTR AS AMOUNT
    , DMBTR_STOCK AS STOCK_VALUE
    , MEINS AS BASE_UNIT
    , CONVERT(DECIMAL(38,20), STOCK_QTY) AS STOCK_QUANTITY_IN_BASE_UNIT
    , ERFME AS ENTRY_UNIT
    , CONVERT(DECIMAL(38,20), ERFMG) AS STOCK_QUANTITY_IN_ENTRY_UNIT
    , CONVERT(DATE, BUDAT) AS POSTING_DATE
    , CONVERT(DATE, CPUDT) AS CREATE_DATE
    , BLDAT AS DOCUMENT_DATE
    , CASE WHEN AEDAT = '00000000' THEN NULL ELSE CONVERT(DATE, AEDAT) END AS UPDATE_DATE
    , MBLNR AS DOCUMENT_NUMBER
    , ZEILE AS DOCUMENT_LINE_ITEM
    , LINE_ID AS LINE_ID
    , EBELN AS PURCHASE_DOCUMENT
    , EBELP AS PURCHASE_LINE_ITEM
    , SMBLN AS ORIGINAL_DOCUMENT_NUM
    , SMBLP AS ORIGINAL_DOCUMENT_LINE
    , XBLNR AS REFERENCE_DOCUMENT
    , VBELN_IM AS DELIVERY_DOCUMENT
    , VBELP_IM AS DELIVER_LINE_ITEM
    , XAUTO AS IS_AUTO_FLG
    , REPLACE(LTRIM(REPLACE(MATDOC.MATNR, '0', ' ')), ' ', '0') AS MATERIAL_NUMBER
    , LGORT AS STORAGE_LOCATION
    , CHARG AS BATCH_NUMBER
    , MATDOC.BWTAR AS VALUATION_TYPE
    , SHKZG AS CR_DR_FLG
    , SGTXT AS [TEXT]
    , MATDOC.VPRSV AS PRICE_INDICATOR
    , BLART AS DOCUMENT_TYPE
    , PRCTR AS PROFIT_CENTER
    , KOSTL AS COST_CENTER
    , ABLAD AS UPLOADING_POINT


    , MBEW.VERPR AS BALANCE


    , CONCAT('~', KEY1, KEY2, KEY3, KEY4, KEY5, KEY6) AS W_INTEGRATION_ID
-- FROM [FND].[W_SAP_MATDOC_F_temp] MATDOC
FROM [STG].[W_SAP_MATDOC_FS_temp] MATDOC
    LEFT JOIN [dbo].[W_PRODUCT_D] PRODUCT ON 
        REPLACE(LTRIM(REPLACE(MATDOC.MATNR, '0', ' ')), ' ', '0') = PRODUCT.PRODUCT_CODE
        AND PRODUCT.W_DATASOURCE_NUM_ID = 1
    LEFT JOIN [dbo].[W_PLANT_SAP_D] PLANT ON PLANT.PLANT_CODE = MATDOC.WERKS
    INNER JOIN [FND].[W_SAP_MBEW_D] MBEW ON MBEW.MATNR = MATDOC.MATNR

WHERE MATDOC.MANDT = '300'
