SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_EXCEL_SPP_WRITE_OFF_FROMREUSE_F]
(
	[PLANT] [nvarchar](10) NULL,
	[PERIOD] [bigint] NULL,
	[WRITEOFF_REUSE] DECIMAL(38, 20) NULL,
	[FILE_NAME] [nvarchar](100) NULL,

	[W_INSERT_DT] [datetime2] NULL,
	[W_UPDATE_DT] [datetime2] NULL,
	[W_BATCH_ID] [bigint] NULL,
	[W_DATASOURCE_NUM_ID] [nvarchar](2) NULL,
	[W_DELETE_FLG] [nvarchar](2) NULL,
	[W_INTEGRATION_ID] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
