SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_EXCEL_SPP_MAPPING_COSTCENTER_D]
(
	[COST_CENTER] NVARCHAR(30) NULL
	, [DESCRIPTION] NVARCHAR(1000) NULL
	, [PL_LINE] NVARCHAR(50) NULL
	, [PL_LINE_FOR_COSTCENTER_LINE] NVARCHAR(50) NULL
	, [LOCATION] NVARCHAR(30) NULL
	, [GENERAL_NAME] NVARCHAR(100) NULL
	, [LINE] NVARCHAR(20) NULL
	, [GENERAL_NAME_COSTCENTER] NVARCHAR(100) NULL
	
	, [FILE_PATH] [nvarchar](100) NULL

	, [W_INSERT_DT] DATETIME2 NULL
	, [W_UPDATE_DT] DATETIME2 NULL
	, [W_BATCH_ID] BIGINT NULL
	, [W_DATASOURCE_NUM_ID] NVARCHAR(2) NULL
	, [W_DELETE_FLG] NVARCHAR(2) NULL
	, [W_INTEGRATION_ID] NVARCHAR(4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO



DECLARE @date DATETIME2 = DATEADD(HH, 7, GETDATE());

INSERT INTO [FND].[W_EXCEL_SPP_MAPPING_COSTCENTER_D](
	[COST_CENTER] 
	, [DESCRIPTION]
	, [PL_LINE] 
	, [PL_LINE_FOR_COSTCENTER_LINE]
	, [LOCATION]
	, [GENERAL_NAME]
	, [LINE]
	, [GENERAL_NAME_COSTCENTER]

	, [FILE_PATH]

	, [W_INSERT_DT]
	, [W_UPDATE_DT]
	, [W_BATCH_ID]
	, [W_DATASOURCE_NUM_ID]
	, [W_DELETE_FLG]
	, [W_INTEGRATION_ID]
)
SELECT 
	[Cost Center]
	, [Description]
	, [P&L line]
	, [P&L line for Cost center Line]
	, [Location]
	, [General Name]
	, [Line]
	, [Cost center General Name]

	, [FILE_PATH]

	, @date
	, @date
	, [W_BATCH_ID]
	, 3
	, 'N'
	, CONCAT([Cost Center], '~', [P&L line], '~', [Location], '~', [Line])

FROM [STG].[W_EXCEL_SPP_MAPPING_COSTCENTER_DS]

select top 10 * from [FND].[W_EXCEL_SPP_MAPPING_COSTCENTER_D];