SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_EXCEL_SPP_LACK_SPP_F]
(
	[ITEM_NUM] [nvarchar](15) NULL,
	[DESCRIPTION] [nvarchar](1000) NULL,
	[WAREHOUSE] NVARCHAR(10) NULL,
	[LACK_SPP] INT,
	[FILE_PATH] [nvarchar](100) NULL,
	[YEAR] INT NULL,
	[MONTH] INT NULL,

	[W_INSERT_DT] [datetime2] NULL,
	[W_UPDATE_DT] [datetime2] NULL,
	[W_BATCH_ID] [bigint] NULL,
	[W_DATASOURCE_NUM_ID] [nvarchar](2) NULL,
	[W_DELETE_FLG] [nvarchar](2) NULL,
	[W_INTEGRATION_ID] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

