SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_EXCEL_SPP_PURCHASE_ORACLE_D]
(
	[MATERIAL] NVARCHAR(100) NULL
	, [VALUATION_TYPE] NVARCHAR(100) NULL
	, [PLANT] NVARCHAR(100) NULL
	, [STORAGE_LOCATION] NVARCHAR(100) NULL
	, [BATCH] NVARCHAR(100) NULL
	, [VALUATION_AREA] NVARCHAR(100) NULL
	, [VALUATION_CLASS] NVARCHAR(100) NULL
	, [TYPE_OF_WAREHOUSE] NVARCHAR(100) NULL
	, [MATERIAL_TYPE] NVARCHAR(100) NULL
	, [MATERIAL_GROUP] NVARCHAR(100) NULL
	, [PURCHASING_GROUP] NVARCHAR(100) NULL
	, [MATERIAL_DESCRIPTION] NVARCHAR(1000) NULL
	, [BASE_UNIT_OF_MEASURE] NVARCHAR(100) NULL
	, [CURRENCY] NVARCHAR(100) NULL
	, [PRICE_CONTROL] NVARCHAR(100) NULL
	, [STOCK_QTY_ON_PERIOD_START] DECIMAL(38, 20) NULL
	, [VALUE_ON_PERIOD_START] DECIMAL(38, 20) NULL
	, [TOTAL_GOODS_RECEIPT_QTY] DECIMAL(38, 20) NULL
	, [TOTAL_GOODS_RECEIPT_VALUE] DECIMAL(38, 20) NULL
	, [TOTAL_GOODS_ISSUE_QTY] DECIMAL(38, 20) NULL
	, [TOTAL_GOODS_ISSUE_VALUE] DECIMAL(38, 20) NULL
	, [STOCK_QTY_ON_PERIOD_END] DECIMAL(38, 20) NULL
	, [STOCK_VALUE_ON_PERIOD_END] DECIMAL(38, 20) NULL
	, [SOURCE_OF_INFORMATION] NVARCHAR(100) NULL
	, [OB_QTY] DECIMAL(38, 20) NULL
	, [OB_ORACLE_PRICE] DECIMAL(38, 20) NULL
	, [OB_BALANCE] DECIMAL(38, 20) NULL
	, [TRANSFER_QTY] DECIMAL(38, 20) NULL
	, [TRANSFER_AMOUNT] DECIMAL(38, 20) NULL
	, [OB_AMOUNT] DECIMAL(38, 20) NULL
	, [GR_QTY] DECIMAL(38, 20) NULL
	, [GR_AMOUNT] DECIMAL(38, 20) NULL
	, [GI_QTY] DECIMAL(38, 20) NULL
	, [GI_PRICE] DECIMAL(38, 20) NULL
	, [GI_AMOUNT] DECIMAL(38, 20) NULL
	, [OTHER_TRANSFER_QTY] DECIMAL(38, 20) NULL
	, [OTHER_TRANSFER_AMOUNT] DECIMAL(38, 20) NULL
	, [CB_QTY] DECIMAL(38, 20) NULL
	, [CB_AMOUNT] DECIMAL(38, 20) NULL
	
	, [FILE_PATH] [nvarchar](100) NULL
	, [PERIOD] INT NULL

	, [W_INSERT_DT] DATETIME2 NULL
	, [W_UPDATE_DT] DATETIME2 NULL
	, [W_BATCH_ID] BIGINT NULL
	, [W_DATASOURCE_NUM_ID] NVARCHAR(2) NULL
	, [W_DELETE_FLG] NVARCHAR(2) NULL
	, [W_INTEGRATION_ID] NVARCHAR(4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
