SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_EXCEL_SPP_BALANCE_FORECAST_F]
(
	[PLANT] NVARCHAR(10) NULL
	, [TYPE] NVARCHAR(10) NULL
	, [BALANCE] DECIMAL(38, 20) NULL
	, [YEAR] INT NULL
	, [MONTH] INT NULL	
	
	, [FILE_PATH] [nvarchar](100) NULL

	, [W_INSERT_DT] DATETIME2 NULL
	, [W_UPDATE_DT] DATETIME2 NULL
	, [W_BATCH_ID] BIGINT NULL
	, [W_DATASOURCE_NUM_ID] NVARCHAR(2) NULL
	, [W_DELETE_FLG] NVARCHAR(2) NULL
	, [W_INTEGRATION_ID] NVARCHAR(4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
