SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_EXCEL_SPP_MAPPING_SLOC_SAP_CMMS_D]
(
	[SAP_PLANT] [nvarchar](10) NULL,
	[SAP_PLANT_DESCRIPTION] [nvarchar](1000) NULL,
	[SAP_STO_LOC] [nvarchar](10) NULL,
	[SAP_STO_LOC_DESCRIPTION] [nvarchar](1000) NULL,

	[CMMS_PLANT] NVARCHAR(10) NULL,
	[CMMS_STO_LOC] [nvarchar](10) NULL,
	[CMMS_STO_LOC_DESCRIPTION] [nvarchar](1000) NULL,

	[W_INSERT_DT] [datetime2] NULL,
	[W_UPDATE_DT] [datetime2] NULL,
	[W_BATCH_ID] [bigint] NULL,
	[W_DATASOURCE_NUM_ID] [nvarchar](2) NULL,
	[W_DELETE_FLG] [nvarchar](2) NULL,
	[W_INTEGRATION_ID] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
