SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_EXCEL_SPP_PURCHASE_TARGET_F]
(
	[PLANT] [nvarchar](5) NULL
	, [PURCHASE_TARGET] DECIMAL(38, 20) NULL
	, [BALANCE_TARGET] DECIMAL(38, 20) NULL
	, [YEAR] INT NULL
	, [FILE_PATH] [nvarchar](100) NULL

	, [W_INSERT_DT] [datetime2] NULL
	, [W_UPDATE_DT] [datetime2] NULL
	, [W_BATCH_ID] [bigint] NULL
	, [W_DATASOURCE_NUM_ID] [nvarchar](2) NULL
	, [W_DELETE_FLG] [nvarchar](2) NULL
	, [W_INTEGRATION_ID] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

