select  
    shkzg = H,S
    BWART AS MOVEMENTYPE,
    MATNR AS MATERIAL CODE,
    LGORT AS STORAGE_LOCATION,
    CHARG AS BATCH_NUMBER,
    LIFNR AS VENDOR
    BUDAT AS POSTING_DATE,
    STOCK_QTY
    DMBTR_STOCK
    MEIN - BASE QTY
    WAERS - CURRENCY CODE: VND, JPY -->  DMBTR_STOCK*100
    WERKS - PLANT CODE
FROM 