SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_EXCEL_SPP_PURCHASE_F]
(
	[PLANT_WID] INT NULL,
	[PLANT_NAME] [nvarchar](100) NULL,
	[LINE] [nvarchar](100) NULL,
	[MACHINE] [nvarchar](100) NULL,
	[ITEM_CODE] [nvarchar](100) NULL,
	[DESCRIPTION] [nvarchar](1000) NULL,
	[CODE] [nvarchar](100) NULL,
	[MANUFACTURER] [nvarchar](100) NULL,
	[UOM] [nvarchar](100) NULL,

	[PRICE] DECIMAL(38, 20) NULL,
	[QUANTITY] FLOAT NULL,
	[OVH] FLOAT NULL,
	[PM] FLOAT NULL,
	[CM] FLOAT NULL,
	[CRITICAL_SPARE] FLOAT NULL,
	[NEEDED_QTY] FLOAT NULL,
	[MIN_LEVEL] FLOAT NULL,
	[MAX_LEVEL] FLOAT NULL,
	[AVG_LEVEL] FLOAT NULL,
	[PERIOD] [bigint] NULL,
	[PURCHASING] FLOAT NULL,
	
	[FILE_NAME] [nvarchar](100) NULL,

	[W_INSERT_DT] [datetime2] NULL,
	[W_UPDATE_DT] [datetime2] NULL,
	[W_BATCH_ID] [bigint] NULL,
	[W_DATASOURCE_NUM_ID] [nvarchar](2) NULL,
	[W_DELETE_FLG] [nvarchar](2) NULL,
	[W_INTEGRATION_ID] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
