SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[W_EXCEL_SPP_LINE_CATEGORY_F]
(
	[LINE_CAT_WID] INT NULL,

	[LINE_ASSET_UID] NVARCHAR(30) NULL,
	[LINE_ASSET_NUM] [nvarchar](100) NULL,
	[CATEGORY] [nvarchar](100) NULL,	
	[FROM_DATE] datetime2 NULL,
	[TO_DATE] datetime2 NULL,

	[W_INSERT_DT] datetime2 NULL,
	[W_UPDATE_DT] datetime2 NULL,
	[W_BATCH_ID] bigint NULL,
	[W_DATASOURCE_NUM_ID] [nvarchar](2) NULL,
	[W_DELETE_FLG] [nvarchar](2) NULL,
	[W_INTEGRATION_ID] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO