SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[W_EXCEL_SPP_J3RFLVMOBVEDH_F] (
	[MATERIAL_WID] INT NULL
	, [DATE_WID] INT NULL
	, [PLANT_WID] INT NULL

	, [MATERIAL] NVARCHAR(10) NULL
	, [VALUATION_TYPE] NVARCHAR(10) NULL
	, [PLANT] NVARCHAR(5) NULL
	, [STORAGE_LOCATION] NVARCHAR(5) NULL
	, [BATCH] NVARCHAR(10) NULL
	, [COMPANY_CODE] NVARCHAR(5) NULL
	, [VALUATION_AREA] NVARCHAR(5) NULL
	, [VALUATION_CLASS] NVARCHAR(5) NULL
	, [GL_ACCOUNT] NVARCHAR(100) NULL
	, [MATERIAL_TYPE] NVARCHAR(5) NULL
	, [MATERIAL_GROUP] NVARCHAR(8) NULL
	, [EXT_MATERIAL_GROUP] NVARCHAR(100) 
	, [OLD_MATERIAL_NUMBER] NVARCHAR(10) NULL
	, [PURCHASING_GROUP] NVARCHAR(5) NULL
	, [MATERIAL_DESCRIPTION] NVARCHAR(1000) NULL
	, [BASE_UNIT_OF_MEASURE] NVARCHAR(5) NULL
	, [CURRENCY] NVARCHAR(5) NULL
	, [PRICE_CONTROL] NVARCHAR(3) NULL
	, [STOCK_QUANTITY_ON_PERIOD_START] DECIMAL(38, 20) NULL
	, [VALUE_ON_PERIOD_START] DECIMAL(38, 20) NULL
	, [TOTAL_GOODS_RECEIPT_QUANTITY] DECIMAL(38, 20) NULL
	, [TOTAL_GOODS_RECEIPT_VALUE] DECIMAL(38, 20) NULL
	, [TOTAL_GOODS_ISSUE_QUANTITY] DECIMAL(38, 20) NULL
	, [TOTAL_GOODS_ISSUE_VALUE] DECIMAL(38, 20) NULL
	, [STOCK_QUANTITY_ON_PERIOD_END] DECIMAL(38, 20) NULL
	, [STOCK_VALUE_ON_PERIOD_END] DECIMAL(38, 20) NULL
	, [RECEIPT_FROM_PURCHASE_QUANTITY] DECIMAL(38, 20) NULL
	, [RECEIPT_FROM_PURCHASE_VALUE] DECIMAL(38, 20) NULL
	, [ISSUE_TO_SALES_QUANTITY] DECIMAL(38, 20) NULL
	, [ISSUE_TO_SALES_VALUE] DECIMAL(38, 20) NULL
	, [RECEIPT_FROM_MANUFACT_QUANTITY] DECIMAL(38, 20) NULL
	, [RECEIPT_FROM_MANUFACT_VALUE] DECIMAL(38, 20) NULL
	, [ISSUE_TO_MANUFACT_QUANTITY] DECIMAL(38, 20) NULL
	, [ISSUE_TO_MANUFACT_VALUE] DECIMAL(38, 20) NULL
	, [RECEIPT_FROM_TRANSFER_QUANTITY] DECIMAL(38, 20) NULL
	, [RECEIPT_FROM_TRANSFER_VALUE] DECIMAL(38, 20) NULL
	, [ISSUE_TO_TRANSFER_QUANTITY] DECIMAL(38, 20) NULL
	, [ISSUE_TO_TRANSFER_VALUE] DECIMAL(38, 20) NULL
	, [QUANTITY_OF_OTHER_RECEIVED_GOODS] DECIMAL(38, 20) NULL
	, [VALUE_OF_OTHER_RECEIVED_GOODS] DECIMAL(38, 20) NULL
	, [QUANTITY_OF_OTHER_ISSUED_GOODS] DECIMAL(38, 20) NULL
	, [VALUE_OF_OTHER_ISSUED_GOODS] DECIMAL(38, 20) NULL
	, [ISSUE_TO_INTERNAL_PURPOSES_QTY] DECIMAL(38, 20) NULL
	, [ISSUE_TO_INTERNAL_PURPOSES_VAL] DECIMAL(38, 20) NULL
	, [DEBIT_REVALUATION] DECIMAL(38, 20) NULL
	, [CREDIT_REVALUATION] DECIMAL(38, 20) NULL
	
	, [PERIOD] INT NULL

	, [W_INSERT_DT] DATETIME2 NULL
	, [W_UPDATE_DT] DATETIME2 NULL
	, [W_BATCH_ID] BIGINT NULL
	, [W_DATASOURCE_NUM_ID] NVARCHAR(2) NULL
	, [W_DELETE_FLG] NVARCHAR(2) NULL
	, [W_INTEGRATION_ID] NVARCHAR(4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
