SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[W_EXCEL_SPP_LINE_CATEGORY_DOWNTIME_F]
(
	[PLANT_WID] INT NULL,
	[ASSET_WID] INT NULL,

	[PLANT_NAME] [nvarchar](10) NULL,
	[CATEGORY] [nvarchar](50) NULL,
	[ASSET_NUM] [nvarchar](50) NULL,
	[LINE_DESCRIPTION] [nvarchar](1000) NULL,
	[CODE] NVARCHAR(20) NULL,
	[YEAR_TO_DATE] DECIMAL(38, 20),
	[DOWNTIME] DECIMAL(38, 20),
	[PERIOD] [bigint] NULL,

	[W_INSERT_DT] [datetime2] NULL,
	[W_UPDATE_DT] [datetime2] NULL,
	[W_BATCH_ID] [bigint] NULL,
	[W_DATASOURCE_NUM_ID] [nvarchar](2) NULL,
	[W_DELETE_FLG] [nvarchar](2) NULL,
	[W_INTEGRATION_ID] [nvarchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

SELECT TOP 50 * FROM [dbo].[W_EXCEL_SPP_LINE_CATEGORY_DOWNTIME_F]
WHERE ASSET_NUM = '130340000000';