SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[W_EXCEL_SPP_BALANCE_FORECAST_F] (
	  [DATE_WID] INT NULL
	, [PLANT_WID] INT NULL

	, [PLANT] NVARCHAR(10) NULL
	, [TYPE] NVARCHAR(100) NULL
	, [BALANCE] DECIMAL(38, 20) NULL

	, [W_INSERT_DT] DATETIME2 NULL
	, [W_UPDATE_DT] DATETIME2 NULL
	, [W_BATCH_ID] BIGINT NULL
	, [W_DATASOURCE_NUM_ID] NVARCHAR(2) NULL
	, [W_DELETE_FLG] NVARCHAR(2) NULL
	, [W_INTEGRATION_ID] NVARCHAR(4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
