SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[W_EXCEL_SPP_MARKET_PRICE_F] (
	[DATE_WID] INT NULL
	, [PRODUCT_WID] BIGINT NULL
	, [PLANT_WID] BIGINT NULL

	, [PLANT] [nvarchar](100) NULL
	, [PLANT_NAME] [nvarchar](100) NULL
	, [STORAGE_LOCATION] [nvarchar](100) NULL
	, [MATERIAL_NUMBER] [nvarchar](100) NULL
	, [MARKET_PRICE] DECIMAL(38, 20) NULL
	, [DESCRIPTION] [nvarchar](1000) NULL
	, [BASE_UNIT] [nvarchar](100) NULL
	, [CODE] [nvarchar](100) NULL



	, [W_INSERT_DT] DATETIME2 NULL
	, [W_UPDATE_DT] DATETIME2 NULL
	, [W_BATCH_ID] BIGINT NULL
	, [W_DATASOURCE_NUM_ID] VARCHAR(1) NULL
	, [W_DELETE_FLG] VARCHAR(1) NULL
	, [W_INTEGRATION_ID] NVARCHAR(4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
