SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_CMMS_SERV_F]
(
	[ASSET_NUM] [nvarchar](200) NULL,
	[CHANGEDATE] DATETIME2 NULL,
	[CURRENCY_CODE] [nvarchar](200) NULL,
	[CURRENCY_LINECOST] [real] NULL,
	[CURRENCY_UNITCOST] [real] NULL,
	[DESCRIPTION] [nvarchar](200) NULL,
	[ENTERDATE] DATETIME2 NULL,
	[EXCHANGERATE] [real] NULL,
	[EXTERNALREFID] [nvarchar](200) NULL,
	[FINANCIALPERIOD] [nvarchar](200) NULL,
	[ISSUE_TYPE] [nvarchar](200) NULL,
	[ISSUE_TYPE_DESC] [nvarchar](200) NULL,
	[ITEM_NUM] [nvarchar](200) NULL,
	[LINECOST] [real] NULL,
	[LINETYPE] [nvarchar](200) NULL,
	[LOCATION] [nvarchar](200) NULL,
	[POLINENUM] [bigint] NULL,
	[PONUM] [nvarchar](200) NULL,
	[QUANTITY] [real] NULL,
	[REFWO] [nvarchar](200) NULL,
	[REMARK] [nvarchar](200) NULL,
	[SENDER_SYSID] [nvarchar](200) NULL,
	[SERV_ID] [bigint] NULL,
	[SITE_ID] [nvarchar](200) NULL,
	[SPVB_COSTCENTER] [nvarchar](200) NULL,
	[SPVB_SAPPO] [nvarchar](200) NULL,
	[SPVB_SAPRECEIPT] [nvarchar](200) NULL,
	[SPVB_SAPREMARK] [nvarchar](200) NULL,
	[STATUS] [nvarchar](200) NULL,
	[STATUS_DESCRIPTION] [nvarchar](200) NULL,
	[TRANSDATE] DATETIME2 NULL,
	[UNITCOST] [real] NULL,
	[ACTUALDATE] DATETIME2 NULL,
	[FILE_NAME] NVARCHAR(100) NULL,

	[W_BATCH_ID] [bigint] NULL,
	[W_INSERT_DT] DATETIME2 NULL,
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO
TRUNCATE TABLE [FND].[W_CMMS_SERV_F];
