SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_CMMS_INVT_F]
(
	[ITEM_NUMBER] [nvarchar](1000) NULL,
	[QUANTITY] [real] NULL,
	[STORE_LOCATION] [nvarchar](1000) NULL,
	[BIN_NUMBER] [nvarchar](1000) NULL,
	[W_BATCH_ID] [nvarchar](1000) NULL,
	[W_INSERT_DT] [nvarchar](1000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO
