SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_CMMS_ASSET_D]
(
	[ASSET_UID] [nvarchar](30) NULL,
	[SPVB_COSTCENTER] [nvarchar](30) NULL,
	[CHANGE_DATE] [nvarchar](30) NULL,
	[SPVB_FIXEDASSETNUM] [nvarchar](30) NULL,
	[TOTAL_COST] [real] NULL,
	[STATUS] [nvarchar](30) NULL,
	[STATUS_DESCRIPTION] [nvarchar](30) NULL,
	[TOTAL_DOWNTIME] [real] NULL,
	[ASSET_NUM] [nvarchar](30) NULL,
	[ASSET_TYPE] [nvarchar](30) NULL,
	[SPVB_COSTCENTER_DESCRIPTION] [nvarchar](500) NULL,
	[INV_COST] [real] NULL,
	[ISRUNNING] [nvarchar](30) NULL,
	[LOCATION] [nvarchar](30) NULL,
	[SITE_ID] [nvarchar](30) NULL,
	[ASSET_HIERACHICAL_TYPE] [nvarchar](30) NULL,
	[LINE_ASSET_NUM] [nvarchar](30) NULL,
	[MACHINE_ASSET_NUM] [nvarchar](30) NULL,
	[COMPONENT_ASSET_NUM] [nvarchar](30) NULL,
	[DESCRIPTION] [nvarchar](1000) NULL,

    [FILE_NAME] [nvarchar](100) NULL,
	[W_BATCH_ID] [bigint] NULL,
	[W_INSERT_DT] DATETIME2 NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO
