SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [FND].[W_CMMS_INVE_D]
(
	[ISSUE_UNIT] [nvarchar](30) NULL,
	[MIN_LEVEL] [real] NULL,
	[MAX_LEVEL] [real] NULL,
	[INVE_ID] [nvarchar](50) NULL,
	[SITE_ID] [bigint] NULL,
	[STATUS_DESC] [nvarchar](1000) NULL,
	[ORDER_UNIT] [nvarchar](30) NULL,
	[ITEM_NUM] [nvarchar](30) NULL,
	[LAST_ISSUE_DATE] NVARCHAR(30) NULL,
	[LOCATION] [nvarchar](100) NULL,
	[FILE_NAME] [nvarchar](100) NULL,

	[W_BATCH_ID] BIGINT NULL,
	[W_INSERT_DT] DATETIME2 NULL,
	[W_DELETE_FLG] VARCHAR(1) NULL,
    [W_DATASOURCE_NUM_ID] INT NULL,
    [W_INTEGRATION_ID] NVARCHAR(1000) NULL,
	[W_UPDATE_DT] DATETIME2 NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO
