SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_CMMS_ASSET_D]
(
	  [ASSET_UID] BIGINT NULL
	, [ASSET_NUM] NVARCHAR(30) NULL
	, [LOCATION] NVARCHAR(30) NULL
	, [SITE_ID] NVARCHAR(30) NULL
	, [DESCRIPTION] NVARCHAR(1000) NULL

	, [ANCESTOR] NVARCHAR(30) NULL
	, [ASSET_TYPE] NVARCHAR(30) NULL
	, [SPVB_COSTCENTER_DESCRIPTION] NVARCHAR(500) NULL
	, [INV_COST] DECIMAL(38, 20) NULL
	, [IS_RUNNING] INT NULL
	, [SPVB_COSTCENTER] NVARCHAR(30) NULL
	, [TOTAL_COST] [real] NULL
	, [STATUS_DESCRIPTION] NVARCHAR(30) NULL
	, [SPVB_FIXEDASSETNUM] NVARCHAR(30) NULL
	, [CHANGE_DATE] DATETIME2 NULL
	, [TOTAL_DOWNTIME] DECIMAL(38, 20) NULL
	, [STATUS] NVARCHAR(10) NULL
	, [SPVB_BOTTLENECK] INT NULL

    , [FILE_NAME] NVARCHAR(100) NULL

	, [W_BATCH_ID] INT NULL
	, [W_INSERT_DT] DATETIME2 NULL
	, [W_DELETE_FLG] VARCHAR(1) NULL
    , [W_DATASOURCE_NUM_ID] INT NULL
    , [W_INTEGRATION_ID] NVARCHAR(1000) NULL
	, [W_UPDATE_DT] DATETIME2 NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO
