SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_CMMS_ASSET_STATUS_F]
(
	[ASSETSTATUS_ID] BIGINT NULL
	, [FROMDATE] DATETIME2 NULL
	, [TODATE] DATETIME2 NULL
	, [DOWNTIME] FLOAT
	, [CODE] [nvarchar](50) NULL
	, [CODE_DESCRIPTION] [nvarchar](1000) NULL
	, [IS_RUNNING] INT NULL
	, [ASSET_NUM] [nvarchar](20) NULL
	, [ASSET_UID] [bigint] NULL
	, [LOCATION] [nvarchar](20) NULL
	
	, [WONUM] [nvarchar](30) NULL
	, [SPVB_ISSUE] [nvarchar](1000) NULL
	, [SPVB_CA] [nvarchar](200) NULL
	, [SPVB_PA] [nvarchar](100) NULL
	, [REMARKS] [nvarchar](100) NULL
	, [IS_SPLIT] INT NULL
	, [N_SPLIT] INT NULL
	, [FILLER] [nvarchar](500) NULL
	, [FILLER_DOWNTIME] FLOAT NULL

	, [W_INTEGRATION_ID] [nvarchar](4000) NULL
	, [W_BATCH_ID] INT NULL
	, [W_INSERT_DT] DATETIME2 NULL
	, [W_DELETE_FLG] VARCHAR(1) NULL
	, [W_DATASOURCE_NUM_ID] INT NULL
	, [W_UPDATE_DT] DATETIME2 NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO