SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_CMMS_LOC_D]
(
	[DESCRIPTION] [nvarchar](1000) NULL,
	[LOCATION] [nvarchar](1000) NULL,
	[W_BATCH_ID] [nvarchar](1000) NULL,
	[W_INSERT_DT] [nvarchar](1000) NULL
)
GO