SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_CMMS_WO_STATUS_D]
(
	[PARENT] [NVARCHAR](100) NULL,
	[WORKORDER_ID] [NVARCHAR](100) NULL,
	[CHANGEDATE] [NVARCHAR](100) NULL,
	[WOSTATUS_ID] [NVARCHAR](100) NULL,
	[STATUS] [NVARCHAR](100) NULL,
	[FILE_NAME] [NVARCHAR](100) NULL,

	[W_DELETE_FLG] VARCHAR(1) NULL,
    [W_DATASOURCE_NUM_ID] INT NULL,
    [W_INTEGRATION_ID] [NVARCHAR](1000) NULL,
    [W_INSERT_DT] DATETIME2 NULL,
    [W_UPDATE_DT] DATETIME2 NULL,
    [W_BATCH_ID] INT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO
