SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FND].[W_CMMS_ASSET_ANCESTOR_D]
(
	[ASSETANCESTOR_ID] BIGINT NULL
	, [HIERARCHY_LEVELS] INT NULL
	, [ANCESTOR] [nvarchar](100) NULL
	, [ASSET_UID] bigint NULL

	, [FILE_NAME] [nvarchar](100) NULL

	, [W_INSERT_DT] DATETIME2 NULL
	, [W_UPDATE_DT] DATETIME2 NULL
	, [W_BATCH_ID] BIGINT NULL
	, [W_DATASOURCE_NUM_ID] NVARCHAR(2) NULL
	, [W_DELETE_FLG] NVARCHAR(2) NULL
	, [W_INTEGRATION_ID] NVARCHAR(4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO
