EXEC [dbo].[HL_utils_rmTabl] 'dbo.HL_ETL_JOB'
CREATE TABLE dbo.HL_ETL_JOB
(
    JOB_NAME NVARCHAR(100) NOT NULL,
    ETL_TYPE NVARCHAR(5),
    SRC_TABLE NVARCHAR(30),
    TRG_TABLE NVARCHAR(30),
    SRC_FOLDER_NAME NVARCHAR(100),
    TRG_FOLDER_NAME NVARCHAR(100)
)
