SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[W_CMMS_ASSET_D]
(
    [ASSET_WID] INT NOT NULL IDENTITY(1, 1),
    [LOCATION_WID] INT NULL,

    [LINE_ASSET_NUM] [nvarchar](30) NULL,
    [LINE_ASSET_DES] [nvarchar](1000) NULL,
    [SPVB_COSTCENTER] [nvarchar](100) NULL,
    [CHANGE_DATE] DATETIME2 NULL,
    [SPVB_FIXEDASSETNUM] [nvarchar](100) NULL,
    [TOTAL_COST] [real] NULL,
    [STATUS] [nvarchar](100) NULL,
    [STATUS_DESCRIPTION] [nvarchar](100) NULL,
    [TOTAL_DOWNTIME] [real] NULL,
    [ASSET_NUM] [nvarchar](30) NULL,
    [ASSET_TYPE] [nvarchar](100) NULL,
    [SPVB_COSTCENTER_DESCRIPTION] [nvarchar](1000) NULL,
    [INV_COST] [real] NULL,
    [IS_RUNNING] SMALLINT NULL,
    [LOCATION] [nvarchar](100) NULL,
    [SITE_ID] [nvarchar](100) NULL,
    [ASSET_HIERACHICAL_TYPE] [nvarchar](100) NULL,
    [MACHINE_ASSET_NUM] [nvarchar](30) NULL,
    [COMPONENT_ASSET_NUM] [nvarchar](30) NULL,
    [DESCRIPTION] [nvarchar](1000) NULL,

    [W_DELETE_FLG] VARCHAR(1) NULL,
    [W_DATASOURCE_NUM_ID] INT NULL,
    [W_INTEGRATION_ID] [nvarchar](1000) NULL,
    [W_INSERT_DT] DATETIME2 NULL,
    [W_UPDATE_DT] DATETIME2 NULL,
    [W_BATCH_ID] [bigint] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO

alter table [dbo].[W_CMMS_ASSET_D]
ALTER COLUMN LINE_ASSET_DES [nvarchar](1000);

TRUNCATE TABLE [dbo].[W_CMMS_ASSET_D]
SELECT COUNT(*) FROM [FND].[W_CMMS_ASSET_D]
