SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[W_SAP_CSKS_D]
(
    [ASSET_WID] INT IDENTITY(1, 1),

    [MANDT] [nvarchar](255) NULL,
    [KOKRS] [nvarchar](255) NULL,
    [KOSTL] [nvarchar](255) NULL,
    [DATBI] [nvarchar](255) NULL,
    [DATAB] [nvarchar](255) NULL,
    [BKZKP] [nvarchar](255) NULL,
    [PKZKP] [nvarchar](255) NULL,
    [BUKRS] [nvarchar](255) NULL,
    [GSBER] [nvarchar](255) NULL,
    [KOSAR] [nvarchar](255) NULL,
    [VERAK] [nvarchar](255) NULL,
    [VERAK_USER] [nvarchar](255) NULL,
    [WAERS] [nvarchar](255) NULL,
    [KALSM] [nvarchar](255) NULL,
    [TXJCD] [nvarchar](255) NULL,
    [PRCTR] [nvarchar](255) NULL,
    [WERKS] [nvarchar](255) NULL,
    [LOGSYSTEM] [nvarchar](255) NULL,
    [ERSDA] [nvarchar](255) NULL,
    [USNAM] [nvarchar](255) NULL,
    [BKZKS] [nvarchar](255) NULL,
    [BKZER] [nvarchar](255) NULL,
    [BKZOB] [nvarchar](255) NULL,
    [PKZKS] [nvarchar](255) NULL,
    [PKZER] [nvarchar](255) NULL,
    [VMETH] [nvarchar](255) NULL,
    [MGEFL] [nvarchar](255) NULL,
    [ABTEI] [nvarchar](255) NULL,
    [NKOST] [nvarchar](255) NULL,
    [KVEWE] [nvarchar](255) NULL,
    [KAPPL] [nvarchar](255) NULL,
    [KOSZSCHL] [nvarchar](255) NULL,
    [LAND1] [nvarchar](255) NULL,
    [ANRED] [nvarchar](255) NULL,
    [NAME1] [nvarchar](255) NULL,
    [NAME2] [nvarchar](255) NULL,
    [NAME3] [nvarchar](255) NULL,
    [NAME4] [nvarchar](255) NULL,
    [ORT01] [nvarchar](255) NULL,
    [ORT02] [nvarchar](255) NULL,
    [STRAS] [nvarchar](255) NULL,
    [PFACH] [nvarchar](255) NULL,
    [PSTLZ] [nvarchar](255) NULL,
    [PSTL2] [nvarchar](255) NULL,
    [REGIO] [nvarchar](255) NULL,
    [SPRAS] [nvarchar](255) NULL,
    [TELBX] [nvarchar](255) NULL,
    [TELF1] [nvarchar](255) NULL,
    [TELF2] [nvarchar](255) NULL,
    [TELFX] [nvarchar](255) NULL,
    [TELTX] [nvarchar](255) NULL,
    [TELX1] [nvarchar](255) NULL,
    [DATLT] [nvarchar](255) NULL,
    [DRNAM] [nvarchar](255) NULL,
    [KHINR] [nvarchar](255) NULL,
    [CCKEY] [nvarchar](255) NULL,
    [KOMPL] [nvarchar](255) NULL,
    [STAKZ] [nvarchar](255) NULL,
    [OBJNR] [nvarchar](255) NULL,
    [FUNKT] [nvarchar](255) NULL,
    [AFUNK] [nvarchar](255) NULL,
    [CPI_TEMPL] [nvarchar](255) NULL,
    [CPD_TEMPL] [nvarchar](255) NULL,
    [FUNC_AREA] [nvarchar](255) NULL,
    [SCI_TEMPL] [nvarchar](255) NULL,
    [SCD_TEMPL] [nvarchar](255) NULL,
    [SKI_TEMPL] [nvarchar](255) NULL,
    [SKD_TEMPL] [nvarchar](255) NULL,
    [EEW_CSKS_PS_DUMMY] [nvarchar](255) NULL,
    [VNAME] [nvarchar](255) NULL,
    [RECID] [nvarchar](255) NULL,
    [ETYPE] [nvarchar](255) NULL,
    [JV_OTYPE] [nvarchar](255) NULL,
    [JV_JIBCL] [nvarchar](255) NULL,
    [JV_JIBSA] [nvarchar](255) NULL,
    [FERC_IND] [nvarchar](255) NULL,
    [BUDGET_CARRYING_COST_CTR] [nvarchar](255) NULL,
    [AVC_PROFILE] [nvarchar](255) NULL,
    [AVC_ACTIVE] [nvarchar](255) NULL,
    [FUND] [nvarchar](255) NULL,
    [GRANT_ID] [nvarchar](255) NULL,
    [FUND_FIX_ASSIGNED] [nvarchar](255) NULL,
    [GRANT_FIX_ASSIGNED] [nvarchar](255) NULL,
    [FUNC_AREA_FIX_ASSIGNED] [nvarchar](255) NULL,

    [W_DELETE_FLG] VARCHAR(1) NULL,
    [W_DATASOURCE_NUM_ID] INT NULL,
    [W_INTEGRATION_ID] [nvarchar](300) NULL,
    [W_INSERT_DT] [datetime] NULL,
    [W_UPDATE_DT] [datetime] NULL,
    [W_BATCH_ID] [bigint] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
