SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[W_CMMS_ASSET_D]
(
    [ASSET_WID] INT NOT NULL IDENTITY(1, 1)
    , [LOCATION_WID] INT NULL

    , [ASSET_UID] BIGINT NULL
    , [ASSET_NUM] NVARCHAR(30) NULL
    , [ANCESTOR] NVARCHAR(30) NULL
    , [LOCATION] NVARCHAR(50) NULL
    , [SITE_ID] NVARCHAR(50) NULL
    , [DESCRIPTION] NVARCHAR(1000) NULL
    , [ASSET_HIERACHICAL_TYPE] NVARCHAR(100) NULL

    , [LINE_ASSET_NUM] NVARCHAR(30) NULL
    , [LINE_ASSET_DESCRIPTION] NVARCHAR(1000) NULL
    , [MACHINE_ASSET_NUM] NVARCHAR(30) NULL
    , [MACHINE_ASSET_DESCRIPTION] NVARCHAR(1000) NULL
    , [MACHINE_SHORT_NAME] NVARCHAR(500) NULL

    , [ASSET_TYPE] NVARCHAR(100) NULL
    , [SPVB_COSTCENTER_DESCRIPTION] NVARCHAR(1000) NULL
    , [INV_COST] [real] NULL
    , [IS_RUNNING] SMALLINT NULL
    , [SPVB_COSTCENTER] NVARCHAR(100) NULL
    , [CHANGE_DATE] DATETIME2 NULL
    , [SPVB_FIXEDASSETNUM] NVARCHAR(100) NULL
    , [TOTAL_COST] [real] NULL
    , [STATUS_DESCRIPTION] NVARCHAR(100) NULL
    , [TOTAL_DOWNTIME] [real] NULL

    , [W_DELETE_FLG] VARCHAR(1) NULL
    , [W_DATASOURCE_NUM_ID] INT NULL
    , [W_INTEGRATION_ID] NVARCHAR(1000) NULL
    , [W_INSERT_DT] DATETIME2 NULL
    , [W_UPDATE_DT] DATETIME2 NULL
    , [W_BATCH_ID] INT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO